### ISSUE TITLE
[Question] Multiple Cloudflare Account (Multiple API)

### ISSUE THREAD

**Issue by Checkumeito** [EvanTrow/cloudflare-dns#1]
Hello, this is not an issue but a question:
If I have multiple cloudflare accounts with different API, does this work with multiple cloudflare accounts?

**Comment by EvanTrow** [comment]
Yup! You add domains by Zone ID and API Token. You can also import all your domains at once using an API Token.

**Comment by Checkumeito** [comment]
Wonderful, I have been looking for this for ages. I hope you can include other functionality like WAF management and other toggling that CF support too.
